name: GitHub Pages deploy
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create folder & copy files
        run: |
          mkdir basename ${{ github.ref }}
          cp -r en/index.html basename ${{ github.ref }}
          cp -r ru/index.html basename ${{ github.ref }}
          cp -r index.html ${{ github.ref }}
      - name: Create folder site
        run: |
          mkdir site
          cp -r basename ${{ github.ref }} site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: true